to start
	Log "Begin Chrome.start"
	Click "ImagesForNewMaps/SpotlightSearchIcon"
	TypeText "Chrome", Return
	TypeText 
	
end start

to openNewWindow
	Click "ImagesForNewMaps/ChromeFileMenu"
	Click "ImagesForNewMaps/ChromeNewWindowMenu"
	
end openNewWindow

to navigateToGoogleMaps
	TypeText "google.com/maps", Return
	TypeText "google.com/maps",Return
	WaitFor 8.0, "ImagesForNewMaps/ChromeSearchBox"
end navigateToGoogleMaps

to enterWhittendaleDriveAddress
	TypeText "121 Whittendale Drive, 08057",Return
	Click "ImagesForNewMaps/ChromeEarthImage"
	WaitFor 8.0, "ImagesForNewMaps/ChromeWhittendaleDrBuilding"
end enterWhittendaleDriveAddress

to enterCherryHillMallAddress
	Click "ImagesForNewMaps/ChromeAddressSearchBox"
	TypeText CommandKey,"a"
	TypeText "cherry Hill Mall, Cherry Hill NJ",Return
	WaitFor 8.0, "ImagesForNewMaps/ChromeCherryHillMallBuilding"
end enterCherryHillMallAddress

to getDirections
	Click "ImagesForNewMaps/ChromeDirectionsIcon"
	Click "ImagesForNewMaps/Chrome121WhitteodaleDrMoorestownNJGoogleTextImage"
end getDirections

to verifyDirections
	Click "ImagesForNewMaps/ChromeMinimizeExploreOptions"
	Click "ImagesForNewMaps/ChromeWhittendaleDrMoorestownText"
	Click "ImagesForNewMaps/ChromeHideTrafficImage"
	WaitFor 8.0, "ImagesForNewMaps/ChromeRouteforDirections"
	WaitFor 8.0, "ImagesForNewMaps/ChromeRouteforDirections"
end verifyDirections

to closeMapsWindow
	Click "ImagesForNewMaps/ChromeCloseMapsWindow"
end closeMapsWindow





