to start
	Log "Begin Chrome.start"
	Click "SymLinkForImages/SpotlightSearchIcon"
	TypeText "Chrome", Return
	TypeText 
	
end start

to openNewWindow
	Click "SymLinkForImages/ChromeFileMenu"
	Click "SymLinkForImages/ChromeNewWindowMenu"
	
end openNewWindow

to navigateToGoogleMaps url
	TypeText url,Return
	WaitFor 8.0, "SymLinkForImages/ChromeSearchBox"
	Click "SymLinkForImages/ChromeSearchBox"
end navigateToGoogleMaps

to enterWhittendaleDriveAddress
	TypeText "121 Whittendale Drive, 08057",Return
	#	WaitFor 8.0, "SymLinkForImages/ChromeWhittendaleDrBuilding"
end enterWhittendaleDriveAddress

to enterCherryHillMallAddress
	Click "SymLinkForImages/ChromeSearchBox"
	TypeText CommandKey,"a"
	TypeText "cherry Hill Mall, Cherry Hill NJ",Return
	WaitFor 8.0, "SymLinkForImages/ChromeCherryHillMallBuilding"
end enterCherryHillMallAddress

to getDirections
	#	Click "SymLinkForImages/ChromeDirectionsIcon"
	#	Click "SymLinkForImages/Chrome121WhitteodaleDrMoorestownNJGoogleTextImage"
end getDirections

to verifyDirections

	if ImageFound ("SymLinkForImages/ChromeMinimizeExploreOptions") then
		Click "SymLinkForImages/ChromeMinimizeExploreOptions"
	end if
	
	Click "SymLinkForImages/ChromeCarImageTravelOption"
	Click "SymLinkForImages/ChromeWhittendaleDrMoorestownText"
	Click "SymLinkForImages/ChromeHideTrafficImage"
	WaitFor 8.0, "SymLinkForImages/ChromeRouteforDirections"
end verifyDirections

to closeMapsWindow
	Click "SymLinkForImages/ChromeCloseMapsWindow"
end closeMapsWindow





