put the first line of file "/home/autotest/REPO/Initiatives/AutomatedTest/Scenario/eggplant/MultiImageSuite.suite/Images/SymLinkForImages/googleMapsURL.txt" into storedUrl
Log "File contents: " & storedUrl
Log result()

Chrome.start

Chrome.openNewWindow

Chrome.navigateToGoogleMaps storedUrl

Chrome.enterWhittendaleDriveAddress

Chrome.enterCherryHillMallAddress

Chrome.getDirections

Chrome.verifyDirections

Chrome.closeMapsWindow


